
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// CITIES
export const CREATE_CITIES_SUCCESS = "CREATE_CITIES_SUCCESS";
export const DELETE_CITIES_SUCCESS = "DELETE_CITIES_SUCCESS";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const LIST_CITIES_SUCCESS = "LIST_CITIES_SUCCESS";
export const UPDATE_CITIES_SUCCESS = "UPDATE_CITIES_SUCCESS";

// CLASSES
export const CREATE_CLASSES_SUCCESS = "CREATE_CLASSES_SUCCESS";
export const DELETE_CLASSES_SUCCESS = "DELETE_CLASSES_SUCCESS";
export const FINDBY_CLUB_CLASSES_SUCCESS = "FINDBY_CLUB_CLASSES_SUCCESS";
export const FINDBY_STUDENT_CLASSES_SUCCESS = "FINDBY_STUDENT_CLASSES_SUCCESS";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const LIST_CLASSES_SUCCESS = "LIST_CLASSES_SUCCESS";
export const UPDATE_CLASSES_SUCCESS = "UPDATE_CLASSES_SUCCESS";

// CLUBS
export const CREATE_CLUBS_SUCCESS = "CREATE_CLUBS_SUCCESS";
export const DELETE_CLUBS_SUCCESS = "DELETE_CLUBS_SUCCESS";
export const FINDBY_CLASS_CLUBS_SUCCESS = "FINDBY_CLASS_CLUBS_SUCCESS";
export const FINDBY_TEACHER_CLUBS_SUCCESS = "FINDBY_TEACHER_CLUBS_SUCCESS";
export const GET_CLUBS_SUCCESS = "GET_CLUBS_SUCCESS";
export const LIST_CLUBS_SUCCESS = "LIST_CLUBS_SUCCESS";
export const UPDATE_CLUBS_SUCCESS = "UPDATE_CLUBS_SUCCESS";

// COUNTRIES
export const CREATE_COUNTRIES_SUCCESS = "CREATE_COUNTRIES_SUCCESS";
export const DELETE_COUNTRIES_SUCCESS = "DELETE_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const LIST_COUNTRIES_SUCCESS = "LIST_COUNTRIES_SUCCESS";
export const UPDATE_COUNTRIES_SUCCESS = "UPDATE_COUNTRIES_SUCCESS";

// EVENTS
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const FINDBY_CLUB_EVENTS_SUCCESS = "FINDBY_CLUB_EVENTS_SUCCESS";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const LIST_EVENTS_SUCCESS = "LIST_EVENTS_SUCCESS";
export const UPDATE_EVENTS_SUCCESS = "UPDATE_EVENTS_SUCCESS";

// STATES
export const CREATE_STATES_SUCCESS = "CREATE_STATES_SUCCESS";
export const DELETE_STATES_SUCCESS = "DELETE_STATES_SUCCESS";
export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS";
export const LIST_STATES_SUCCESS = "LIST_STATES_SUCCESS";
export const UPDATE_STATES_SUCCESS = "UPDATE_STATES_SUCCESS";

// STUDENTS
export const CREATE_STUDENTS_SUCCESS = "CREATE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const FINDBY_CLASS_STUDENTS_SUCCESS = "FINDBY_CLASS_STUDENTS_SUCCESS";
export const FINDBY_CLUB_STUDENTS_SUCCESS = "FINDBY_CLUB_STUDENTS_SUCCESS";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const LIST_STUDENTS_SUCCESS = "LIST_STUDENTS_SUCCESS";
export const UPDATE_STUDENTS_SUCCESS = "UPDATE_STUDENTS_SUCCESS";

// TEACHERS
export const CREATE_TEACHERS_SUCCESS = "CREATE_TEACHERS_SUCCESS";
export const DELETE_TEACHERS_SUCCESS = "DELETE_TEACHERS_SUCCESS";
export const FINDBY_CLASS_TEACHERS_SUCCESS = "FINDBY_CLASS_TEACHERS_SUCCESS";
export const FINDBY_CLUB_TEACHERS_SUCCESS = "FINDBY_CLUB_TEACHERS_SUCCESS";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const LIST_TEACHERS_SUCCESS = "LIST_TEACHERS_SUCCESS";
export const UPDATE_TEACHERS_SUCCESS = "UPDATE_TEACHERS_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
